---
title: 'kmeans clustering'
author: "[Orhan Aktaş](https://www.linkedin.com/in/orhanaktas/)"
date: "14 December 2020"
output:
  html_document:
    theme: flatly
    df_print: paged
  pdf_document: default
  word_document: default
   
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  #fig.width=12, 
  #fig.height=8, 
  #fig.path='Figs/',
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE)
```

```{r libraries}
library(tidyverse)
library(magrittr)
library(readxl)
library(DT)
library(RColorBrewer)
```


```{r get_data, message=FALSE, warning=FALSE}
file<-"C:/Users/user/Desktop/M5 Measures MCA_new_LocalTeam_EBI.xlsx"
eda_data<-read_excel(file,sheet = "Step1 MCA_rankings") %>% 
  filter(Number!="B1")
measures<-eda_data %>% select(c(1,2))
eda_data<-eda_data[3:11]
head(eda_data)
head(measures)
```


implement kmeans clustering
```{r}
clusters<-kmeans(eda_data,27)
measure_clusters<-measures %>% 
  cbind(clusters$cluster) %>% 
  rename(cluster="clusters$cluster") %>% 
  select(cluster, Measure) %>% 
  arrange(cluster) 
```

with DT formatStyle function in DT package it is possible to change all cells in a row base on a value from a cell in that row. 
```{r}
measure_clusters %>% 
	datatable %>% 
	formatStyle('cluster',
	       fontWeight = "bold",
		     target = 'row',
		     color = styleEqual(
					c(1:27),
					rep(brewer.pal(27,"Set1"),5)[1:27]
				  )
	) 
```



