---
title: 'survey_results_so_far'
author: "[Orhan Aktaş](https://www.linkedin.com/in/orhanaktas/)"
date: "15 December 2020"
output:
  html_document:
    theme: flatly
    df_print: paged
  pdf_document: default
  word_document: default
   
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  #fig.width=12, 
  #fig.height=8, 
  #fig.path='Figs/',
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(magrittr)
library(readxl)
library(DT)
library(RColorBrewer)
library(dendextend)
```

```{r}

folder_path<-"C:/danışmanlık/arup/reports/m5/long list/scores/"

# list files
file_names <- list.files(folder_path)

# file list with paths
file_paths <- paste(folder_path, file_names, sep = "")
  
# import data
data<-file_paths %>% map(read_excel, 
    range = "A5:S84",
    sheet ="Step1 MCA_rankings")

data<-data %>% 
  map(select,-c(3:10))%>% 
  set_names(file_names)%>% 
  map(mutate_at,c(3:11),as.numeric)%>% 
  #map2(file_names,~mutate(.x,file= .y)) %>% 
  imap(~mutate(.x,file= .y)) %>% 
  map(select,1,2,file,3:11) %>% 
  bind_rows%>% 
  mutate(sum=rowSums(.[4:12]))
```

data analysis
```{r echo=FALSE,fig.height = 15}
data %>% pivot_longer(
    !c(1:3,"sum"),
    names_to = "objective",
    values_to = "scores"
  ) %>% 
  group_by(Measure,objective) %>% 
  summarise( 
    mean=mean(scores), 
    sd=sd(scores)) %>% 
  arrange(desc(sd)) ->sd_data

sd_data%>% 
  ggplot()+
  geom_point(mapping=aes(x=mean,y=sd))
par(mar=c(1,1,1,25))
sd_data%>% 
  mutate(obj_mea=paste(Measure,objective,sep = "")) %>% 
  ggplot()+
  geom_col(mapping=aes(x=reorder(obj_mea,sd),y=sd)) +
  theme(text = element_text(size=5))+
  coord_flip()
```

