---
title: 'Survey Results Factor Analysis'
author: "[Orhan Aktaş](https://www.linkedin.com/in/orhanaktas/)"
date: "10 December 2020"
output:
  html_document:
    theme: flatly
    df_print: paged
  pdf_document: default
  word_document: default
   
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  #fig.width=12, 
  #fig.height=8, 
  #fig.path='Figs/',
  echo=FALSE, 
  message=FALSE, 
  warning=FALSE)
```

```{r libraries}
library(googlesheets4)
library(tidyverse)
library(reshape2)
library(heatmaply)
library(psych)
```


```{r get_data, message=FALSE, warning=FALSE}


gs4_deauth()
link<-"https://docs.google.com/spreadsheets/d/1sXxCzr_EadTeXEK_KSMn5WMHI3UkAvF101pRmfK1yMA/edit?usp=sharing"
data<-read_sheet(link)

head(data)
```

# Sample Size and Sample to Variable Ratio
Sample size is `r nrow(data)` and there are `r ncol(data)-2` number of measures in the data set. 



create correlation matrix
```{r}
matrix<-cor(data[3:81],data[3:81])
matrix %>% 
  melt %>% 
  mutate(value=abs(value)) %>% 
  filter(value<0.99) %>% 
  ggplot (mapping=aes(x=value)) + 
  geom_histogram(binwidth = 0.1,boundary =1)+ 
  scale_x_continuous(name="correlation", breaks=seq(0, 1, 0.1),limits = c(0,1)) 
```

the measures of factoring adequacy
or
whether the matrix is factorable

[ref:](https://cran.r-project.org/web/packages/psych/psych.pdf)
```{r}
cortest.bartlett(matrix)
KMO(matrix)
```



heatmap
```{r eval=FALSE, warning=FALSE, include=FALSE}


#png("high_res.png", width = 8, height = 8, units = 'in', res = 1600)
#heatmap(as.matrix(data[3:ncol(data)]))

heatmaply_cor(
  matrix, 
  showticklabels = c(F,F), 
  margins = c(80,10),
  label_format_fun = function(...) round(..., digits = 1))
#dev.off()
```

